apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e20dhsmfg-nodejs 
  janus-idp.io/tekton: e20dhsmfg-nodejs
  backstage.io/kubernetes-id: e20dhsmfg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e20dhsmfg-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml